name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-test-format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Set up Java
              uses: actions/setup-java@v5
              with:
                  distribution: temurin
                  java-version: '25'
                  cache: gradle

            - name: Make Gradle wrapper executable
              run: chmod +x ./gradlew

            - name: Compile project
              run: ./gradlew compileJava

            - name: Run JUnit tests
              run: ./gradlew test

            - name: Check formatting
              run: ./gradlew spotlessCheck
